FROM node:22.11.0-alpine

WORKDIR /app

# Copier les fichiers de configuration du workspace
COPY package.json yarn.lock .npmrc ./
COPY packages/ ./packages/

# Copier le frontend
COPY apps/docs/ ./apps/docs/

# Installer les dépendances depuis la racine (monorepo)
RUN yarn install --frozen-lockfile

# Build le frontend
RUN yarn workspace docs build

EXPOSE 3000

# Démarrer depuis le workspace docs
CMD ["yarn", "workspace", "docs", "start"]