FROM node:22.11.0-alpine

WORKDIR /app

# Copier les fichiers de configuration du workspace
COPY package.json yarn.lock .npmrc ./
COPY packages/ ./packages/

# Copier le frontend
COPY apps/docs/ ./apps/docs/

# Installer les dépendances
RUN yarn install --frozen-lockfile

# Build le frontend
WORKDIR /app/apps/docs
RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]